
"""ftx_data.ipynb

Automatically generated by Colaboratory.



This Project was based on collected data from FTX website using their API

I Collected DATA from 

BTC
ETH
BNB
BCH
LTC
SOL
DOT
AVAX

Importing Required Packages
"""

from datetime import datetime
from dotenv import load_dotenv
import os
import json
import pandas as pd
import requests
import time

from client import FtxClient

def pad_name(pad_last, df):
    old_col_names = list(df.columns)
    new_col_names = []
    for col in old_col_names:
        new_col_names.append(col+pad_last)
    df.rename(dict(zip(old_col_names, new_col_names)), axis=1, inplace=True) 
    return df

assets = ['BTC', 'ETH', 'BNB', 'BCH', 'AVAX', 'SOL', 'LTC']

def collect_data(asset):
    endpoint_url = 'https://ftx.com/api/markets'
    base_currency = asset
    quote_currency = 'USD'

    # Specify the base and quote currencies to get single market data
    request_url = f'{endpoint_url}/{base_currency}/{quote_currency}'

    # 1 day = 60 * 60 * 24 seconds
    daily=str(60*60*24)

    # Start date = 2022-04-01
    start = datetime(2020, 1, 1).timestamp()

    # Get the historical market data as JSON
    historical = requests.get(
        f'{request_url}/candles?resolution={daily}&start_time={start}'
    ).json()

    # Convert JSON to Pandas DataFrame
    df = pd.DataFrame(historical['result'])

    #Convert time to date
    df['date'] = pd.to_datetime(
        df['time']/1000, unit='s', origin='unix'
    ) 

    format = '%Y-%m-%dT%H:%M:%S+00:00'

    df['startTime'] = df['startTime'].apply(lambda x: datetime.strptime(x, format))
    df.rename({'startTime':'timestamp'}, axis=1, inplace = True)
    df.drop(['time', 'date'], axis=1, inplace=True)

    asset_1H = df.set_index('timestamp').resample('1H').pad()
    asset_2H = df.set_index('timestamp').resample('2H').pad()
    asset_4H = df.set_index('timestamp').resample('4H').pad()
    asset_8H = df.set_index('timestamp').resample('8H').pad()
    asset_24H = df.set_index('timestamp').resample('24H').pad()
    asset_48H = df.set_index('timestamp').resample('48H').pad()
    asset_72H = df.set_index('timestamp').resample('72H').pad()

    col_name_change_1H = pad_name("_ftx_1H", asset_1H)
    col_name_change_2H = pad_name("_ftx_2H", asset_2H)
    col_name_change_4H = pad_name("_ftx_4H", asset_4H)
    col_name_change_8H = pad_name("_ftx_8H", asset_8H)
    col_name_change_24H = pad_name("_ftx_24H", asset_24H)
    col_name_change_48H = pad_name("_ftx_48H", asset_48H)
    col_name_change_72H = pad_name("_ftx_72H", asset_72H)

    col_name_change_1H.to_csv(f'{asset}_ftx_1H.csv')
    col_name_change_2H.to_csv(f'{asset}_ftx_2H.csv')
    col_name_change_4H.to_csv(f'{asset}_ftx_4H.csv')
    col_name_change_8H.to_csv(f'{asset}_ftx_8H.csv')
    col_name_change_24H.to_csv(f'{asset}_ftx_24H.csv')
    col_name_change_48H.to_csv(f'{asset}_ftx_48H.csv')
    col_name_change_72H.to_csv(f'{asset}_ftx_72H.csv')
    
    return 1

for asset in assets:
    collect_data(asset)
